CREATE DATABASE sistema;
USE sistema;


DROP TABLE usuario;

CREATE TABLE usuario(
cpf VARCHAR(11) PRIMARY KEY NOT NULL,
nome VARCHAR(50) NOT NULL,
idade VARCHAR(3) NOT NULL,
agendamento DATE NOT NULL,
data_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);